### DISCUSSION TITLE
Date Picker - better highlight disabled days

### DISCUSSION THREAD

**Discussion by boeckMt** [vmware-clarity/ng-clarity#243] [Ideas]
When specifying min and max inputs for available dates on `clrDate`, those who are out of this range get the class [is-disabled](https://github.com/vmware-clarity/ng-clarity/blob/main/projects/angular/src/forms/datepicker/day.ts#L23). 

```html
<clr-date-container>
      <label for="dateControlMax">...</label>
      <input id="dateControlMax" type="date" clrDate formControlName="maxDate"
        [min]="dateRange.min" [max]="dateRange.max" />
</clr-date-container>
```

Dates which are from the next or previous month get the class [is-excluded](https://github.com/vmware-clarity/ng-clarity/blob/main/projects/angular/src/forms/datepicker/day.ts#L22). 

Distinguishing between `disabled` and `excluded` dates is very difficult.

Actually a user can override/extend the css class to get the below behaviour, but I think it would be better to use something like crossing out the numbers as a default.

| actual view | enhanced view  | 
|---|---|
|  ![image](https://user-images.githubusercontent.com/3969484/178950518-2355bb03-07ca-415f-9ae7-fdee333d56c7.png) |  ![image](https://user-images.githubusercontent.com/3969484/178953692-a078d02a-422c-400e-9968-76d4b27adb24.png) | 
|  ![image](https://user-images.githubusercontent.com/3969484/178952247-49d29b29-ab94-4500-bdb7-99a0d08bd265.png) |  ![image](https://user-images.githubusercontent.com/3969484/178953592-76582618-cd87-4df5-bf65-0716ccb19bc5.png) | 

e.g.

```scss

.day-btn.is-disabled {
    position: relative;

    &:before {
      position: absolute;
      content: "";
      left: 0.2em;
      top: 50%;
      right: 0.2em;
      border-top: 1px solid;
      border-color: inherit;

      -webkit-transform: rotate(-45deg);
      -moz-transform: rotate(-45deg);
      -ms-transform: rotate(-45deg);
      -o-transform: rotate(-45deg);
      transform: rotate(-45deg);
    }
  }
```
