### ISSUE TITLE
Signpost signpost-content-header cuts the top of the content body scrollbar if content body too long

### ISSUE THREAD

**Issue by KingMario** [vmware-clarity/ng-clarity#871]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug

While the signpost content body is too long, there will be scrollbar displayed for scrolling.

The signpost-content-header cuts the top of the scrollbar.

## How to reproduce

Goto https://clarity.design/documentation/signposts#examples and use browser inspect to insert some contents to the content body to exceed the max-height of the content body. Then observe the the scrollbar top position while scrolling.

![image](https://github.com/vmware-clarity/ng-clarity/assets/3956876/c1ea3b6b-654c-438f-9b16-31dd1d1fd6dc)

## Expected behavior

The signpost-content-header should not cut the top of the scrollbar.

## Versions

**Clarity version:**

- [x] v13.x
- [x] v15.x
- [ ] Other:

## Additional notes

Recommend to set .signpost-content-body padding-top to 0 and margin-top to the clr-signpost-content-padding value to solve the problem. But then the naming of clr-signpost-content-padding is a little confusing.

```css
  .signpost-content-body {
    @include mixins.css-var(
      padding,
      clr-signpost-content-padding,
      variables.$clr_baselineRem_1,
      variables.$clr-use-custom-properties
    );
    padding-top: 0;
    @include mixins.css-var(
        margin-top,
        clr-signpost-content-padding,
        variables.$clr_baselineRem_1,
        variables.$clr-use-custom-properties
    );
    // ...
  }
```
